### ISSUE TITLE
zeros are getting killed

### ISSUE THREAD

**Issue by ventr1x** [lscgzwd/node-ini-parser#1]
Just a little hint.

The way your parser is removing zeros from a value is kind of bad.
For example we use user files with "password=01234".
In this example the 0 gets removed, destroying the password.
Same goes for "password=0000", only one zero gets returned.

EVERY value in a ini file should be handled as a string.
Luckily I instantly saw this issue and could only wonder what that parse does to other values for no reason at all (too lazy to look into it, I'm faster writing my own).

**Comment by lscgzwd** [comment]
Thanks.
By fix this, I add param `returnNumberAsString`, the default value is true.
